name: Hawker Space

description: Tinkering space of Ryan Hawker

author: Ryan Hawker

author_email: hawkerryan@gmail.com

markdown: redcarpet

highlighter: pygments

permalink: pretty

sass:
    sass_dir: _scss
    
metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
